/**
 * Domain types for the home asset tracking system.
 * These types represent the core business entities and are UI-agnostic.
 * Treat these as stable long-term contracts.
 */

export type AttributeType = "text" | "number" | "date" | "file";

export interface ItemAttribute {
  id: string;
  key: string;
  type: AttributeType;
  value: string;
}

export interface Item {
  id: string;
  name: string;
  quantity: number;
  notes?: string;

  /** Hierarchical location stored as path segments, e.g., ["Living Room", "TV Stand", "Drawer"] */
  locationPath: string[];

  attributes: ItemAttribute[];
}

/**
 * Input type for creating a new item.
 * Omits the id field which is generated by the repository.
 */
export type NewItem = Omit<Item, "id">;

/**
 * Input type for creating a new attribute.
 * Omits the id field which is generated by the caller.
 */
export type NewItemAttribute = Omit<ItemAttribute, "id">;
